# Generated by Django 4.2.1 on 2023-06-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
