# Generated by Django 4.2.1 on 2023-06-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='duration',
        ),
    ]
